[build]
  command = "npm run build"
  publish = "build"

[[plugins]]
  package = "@netlify/plugin-prerender-spa"
  inputs = { crawl = true, inlineCss = true, allPageFiles = false }

[[redirects]]
  from = "/game/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true